data_window:
  start: "2025-08-15 21:05"
  end: "2025-11-17 23:00"
  count: 0
plots:
  # type类型： Line：线段，两个端点的， Straight:直线， Candle:表示K线， Curve：曲线，例MA5
  -
    max_height: 0
    chart_item:
    -
      file_name: "D:/new_tdx/T0002/export/28#SRL9.txt"
      type: Candle
    -
      file_name: "均线"
      type: Line
      params: ["MA20", "MA60"]
      func_name: fn_calc_ma20_60
    -
      file_name: "笔"
      type: Straight
      params: []
      func_name: fn_calc_bi
    -
      file_name: ""
      func_name: fn_calc_seg
      params: []
      type: Straight
    -
      file_name: ""
      func_name: fn_calc_bi_pivot
      params: []
      type: Straight
    # - file_name: ""
    #   func_name: fn_calc_duan_pivot
    #   params: []
    #   type: Straight
  -
    max_height: 120
    chart_item:
    -
      file_name: ""
      func_name: fn_calc_macd
      type: Macd
  -
    max_height: 120
    chart_item:
    -
      file_name: ""
      func_name: fn_calc_up_lower_upper
      type: Signal
